env:
  GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Issue-Backport:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository code
      uses: actions/checkout@v4
    - continue-on-error: true
      run: etc/scripts/actions/create-backport-issues.sh $GITHUB_REPOSITORY ${{ github.event.inputs.issue
        }} ${{ github.event.inputs.version }} ${{ github.event.inputs.target-2 }}
        ${{ github.event.inputs.target-3 }} ${{ github.event.inputs.target-4 }}
name: Create Backport Issues
on:
  repository_dispatch:
    types: trigger-ga___create-backport-issues.yml
