concurrency:
  cancel-in-progress: false
  group: release-${{ github.workflow }}-${{ github.ref }}
env:
  JAVA_DISTRO: oracle
  JAVA_VERSION: '21'
  MAVEN_HTTP_ARGS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3
jobs:
  deploy:
    environment: release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      env:
        MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
        RELEASE_WORKFLOW: 'true'
      name: Build and deploy
      run: 'etc/scripts/release.sh deploy_snapshot

        '
    timeout-minutes: 60
name: Snapshot Release
on:
  repository_dispatch:
    types: trigger-ga___snapshotrelease.yaml
