concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  HELIDON_PIPELINES: 'true'
  JAVA_DISTRO: oracle
  JAVA_VERSION: '21'
  MAVEN_HTTP_ARGS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3
jobs:
  archetypes:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Test archetypes
      run: etc/scripts/test-archetypes.sh
    strategy:
      matrix:
        os:
        - ubuntu-20.04
    timeout-minutes: 45
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Maven build
      run: etc/scripts/github-build.sh
    strategy:
      matrix:
        os:
        - ubuntu-20.04
    timeout-minutes: 60
  checkstyle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Checkstyle
      run: etc/scripts/checkstyle.sh
    timeout-minutes: 10
  copyright:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Copyright
      run: etc/scripts/copyright.sh
    timeout-minutes: 10
  docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Docs
      run: etc/scripts/docs.sh
    timeout-minutes: 30
  examples:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Maven build
      run: "mvn -B -e \"-Dmaven.test.skip=true\" $MAVEN_HTTP_ARGS -DskipTests -Ppipeline\
        \ install \ncd examples\nmvn -B verify\n"
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - macos-14
    timeout-minutes: 30
  mp-tck:
    name: MicroProfile TCKs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Maven build
      run: etc/scripts/mp-tck.sh
    strategy:
      matrix:
        os:
        - ubuntu-20.04
    timeout-minutes: 60
  packaging:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: graalvm/setup-graalvm@v1
      with:
        cache: maven
        distribution: graalvm-community
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: 21
        native-image-job-reports: true
    - continue-on-error: true
      name: Build Helidon
      run: etc/scripts/github-compile.sh
    - continue-on-error: true
      name: JAR packaging
      run: etc/scripts/test-packaging-jar.sh
    - continue-on-error: true
      name: JLink packaging
      run: etc/scripts/test-packaging-jlink.sh
    - continue-on-error: true
      name: Native-Image packaging
      run: etc/scripts/test-packaging-native.sh
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - macos-14
    timeout-minutes: 60
  spotbugs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4.1.0
      with:
        cache: maven
        distribution: ${{ env.JAVA_DISTRO }}
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Spotbugs
      run: etc/scripts/spotbugs.sh
    timeout-minutes: 45
name: Validate
on:
  repository_dispatch:
    types: trigger-ga___validate.yml
